#!/usr/bin/env python3

import csv
import json
import math
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXPORT = Path("/Users/jauniuskadunas/Downloads/JcGN4_c1T0OIgOa7EPDYjQ")
OUTPUT = ROOT / "src" / "data" / "articles.generated.ts"


def strip_text(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def truncate(value: str, limit: int = 180) -> str:
    if len(value) <= limit:
        return value
    return value[: limit - 1].rsplit(" ", 1)[0] + "…"


def estimate_reading_time(text: str) -> str:
    words = max(1, len(text.split()))
    minutes = max(1, math.ceil(words / 200))
    return f"{minutes} min read"


def clean_fragment(raw_html: str) -> tuple[str, str]:
    soup = BeautifulSoup(raw_html, "html.parser")

    for node in soup.select("script, style, button, svg, source, .image-link-expand"):
        node.decompose()

    for node in soup.select("picture"):
        image = node.find("img")
        if image:
            node.replace_with(image)
        else:
            node.decompose()

    for node in soup.select(".captioned-image-container, .image2-inset, .available-content"):
        node.unwrap()

    for node in soup.select("a.image-link"):
        node.unwrap()

    for node in soup.find_all("div"):
        children = [child for child in node.children if getattr(child, "name", None) or strip_text(str(child))]
        if len(children) == 1 and getattr(children[0], "name", None) == "hr":
            node.replace_with(children[0])

    allowed = {
        "p",
        "h2",
        "h3",
        "h4",
        "ul",
        "ol",
        "li",
        "a",
        "blockquote",
        "hr",
        "figure",
        "figcaption",
        "img",
        "strong",
        "em",
        "code",
    }

    for tag in list(soup.find_all(True)):
        if tag.name not in allowed:
            tag.unwrap()
            continue

        if tag.name == "img":
            attrs = {}
            for key in ("src", "alt", "width", "height"):
                value = tag.get(key)
                if value:
                    attrs[key] = value
            attrs["loading"] = "lazy"
            tag.attrs = attrs
        elif tag.name == "a":
            href = tag.get("href")
            tag.attrs = {"href": href} if href else {}
        else:
            tag.attrs = {}

    excerpt = ""
    for paragraph in soup.find_all("p"):
        text = strip_text(paragraph.get_text(" ", strip=True))
        if text:
            excerpt = truncate(text)
            break

    for paragraph in list(soup.find_all("p")):
        if not strip_text(paragraph.get_text(" ", strip=True)):
            paragraph.decompose()

    html = "".join(str(node) for node in soup.contents).strip()
    return html, excerpt


def build_article(row: dict[str, str], posts_dir: Path) -> dict[str, str]:
    post_id = row["post_id"]
    html_path = posts_dir / f"{post_id}.html"
    raw_html = html_path.read_text()
    body_html, excerpt = clean_fragment(raw_html)
    slug = post_id.split(".", 1)[1]
    published_at = row["post_date"].split("T", 1)[0]
    title = row["title"].strip()
    subtitle = row["subtitle"].strip()
    description = subtitle or excerpt
    plain_text = strip_text(BeautifulSoup(body_html, "html.parser").get_text(" ", strip=True))

    return {
        "slug": slug,
        "title": title,
        "subtitle": subtitle,
        "description": description,
        "excerpt": excerpt,
        "publishedAt": published_at,
        "readingTime": estimate_reading_time(plain_text),
        "bodyHtml": body_html,
    }


def main() -> int:
    export_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_EXPORT
    posts_csv = export_dir / "posts.csv"
    posts_dir = export_dir / "posts"

    if not posts_csv.exists():
        raise SystemExit(f"Missing posts.csv at {posts_csv}")

    rows = list(csv.DictReader(posts_csv.open()))
    articles = [
        build_article(row, posts_dir)
        for row in rows
        if row.get("is_published") == "true" and row.get("title")
    ]
    articles.sort(key=lambda article: article["publishedAt"], reverse=True)

    OUTPUT.write_text(
        "// Generated by scripts/import_substack_export.py\n"
        f"export const articles = {json.dumps(articles, ensure_ascii=False, indent=2)} as const;\n"
    )
    print(f"Wrote {len(articles)} articles to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
